languaje: python
python:
    - "3.8"
install:
    - pip install -r requirements.txt
script:
    - coverage run test_partida.py 
    - coverage run test_ahorcado.py 
after_success:
    - coveralls
    - coveralls
